### ISSUE TITLE
(Question) Launcher support

### ISSUE THREAD

**Issue by LeonanCarvalho** [npetrovski/l2js-client#11]
Can I use it for a launcher based on electron or other javascript compatible?

The idea is replace the login page and jump to server selection (like official clients do)

**Comment by npetrovski** [comment]
I see no reason why not :) As long as you can execute a JS interpreter and have an API for Socket connection, it should be possible. Take a look at the https://github.com/npetrovski/l2js-client/tree/master/src/socket folder and the adapter for the socket connection - you may need to write your own that works with electron.
