### ISSUE TITLE
Hi, I can't check the client's work.

### ISSUE THREAD

**Issue by gromov-io** [npetrovski/l2js-client#20]
Hi, I can't check the client's work.

Server: test depmax64 High Five
http://www.depmax64.com/forum/index.php?threads/publichnye-testovye-servera.1928/

```
  Username: "test254",
  Password: "test",
  Ip: "35.156.119.94",
  ServerId: 1,
  CharSlotIndex: 0
```

![image](https://user-images.githubusercontent.com/46241127/103485870-99171b80-4e0a-11eb-8caf-b3204ffe6ca1.png)

Server: https://www.rpg-club.com/

```
  Username: "zzgromov",
  Password: "etumonfn",
  Ip: "185.71.66.32",
  ServerId: 1,
  CharSlotIndex: 0
```
![image](https://user-images.githubusercontent.com/46241127/103485903-d8de0300-4e0a-11eb-8c16-2a8eca1dac3f.png)

Please tell me maybe I'm doing something wrong ?
My goal is to get `ServerList` after authorization

**Comment by npetrovski** [comment]
@gromov-io most probably those servers are GG protected.
