### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by ArtemZip** [npetrovski/l2js-client#24]
Hi, 

Can you provide also some additional info to example (like logs example of successful entering, images or even a video) ?

I'm asking because I cannot compile your examples, but I have made my own, which cannot enter.

For example none of printing msgs are shown:
```ts
const l2 = new Client();
l2.enter({
    /* required */ Username: "art",
    /* required */ Password: "1111",
    /* required */ Ip: "127.0.0.1"
})
.then(() => console.log("then"))
.catch(() => console.log("catch"))
.finally(() => console.log("finally"));
```

Thanks a lot

**Comment by npetrovski** [comment]
You can try to increase the log-level by adding the following on top of your code:

```js
const process = require("process");
process.env.L2JSC_LOG_LEVEL = 8;
```

, and observe the log messages
