### ISSUE TITLE
Bot death location

### ISSUE THREAD

**Issue by loykean** [npetrovski/l2js-client#28]
In current version, when bot has been killed, it will stay at same location in death state.

It will not move to nearest town, is it possible to implement this?

**Comment by npetrovski** [comment]
Everything is possible, it is just a matter of time :-)

As soon as I have more time, I will work on that. In the meanwhile, and since the project is an open-source one, you are welcome to implement it and send a merge request.

Cheers.

**Comment by loykean** [comment]
thank you  ;)

**Comment by npetrovski** [comment]
https://npetrovski.github.io/l2js-client/guide/examples.html#revive
