### ISSUE TITLE
Error after RequestCharacters

### ISSUE THREAD

**Issue by AlexKehl** [npetrovski/l2js-client#3]
Hello, I managed to connect successfully to the server but then after RequestCharacters packet was sent I get an uncatched error. I know that this doesn't fit into the 'Issues' section entirely but I found no other way to contact the author.
I am not sure if this has to do with the wrong server id... there are 5 servers and I don't know which id corresponds to which server.
Below I attached a screenshot of the error:
![image](https://user-images.githubusercontent.com/45937479/81474291-c1f7fa00-9204-11ea-89ea-089e2bb866b1.png)

**Comment by npetrovski** [comment]
Hi,yes - this is the right place for this issue.

 From what I can see here - yes indeed, upon sending RequestCharacters the server disconnects, but why exactly aint clear enough.

I can try to reproduce this issue on my side, but for that I will need more information.

1) Is this s public server, if so, what's the IP address?
2) What L2 chronicle is this (its even better if you know the protocol version)?
3) Do you know if there is a GameGuard protection enabled from server side? If so, I am afraid this is not the target of this project - indeed to hack and workaround a GG protection.

**Comment by AlexKehl** [comment]
Thx for answering :) Okay - let's go through the steps:
1. Yes, this is a public server. I checked the ip's through log in process with netstat - this is what I've got:
- The ip immediately after logging in with credentials differs from time to time. But basically it is in range of 185.71.66.16:2106 - 185.71.66.33:2106. I suggest trying 185.71.66.16:2106
- After I've selected the server, port changes to 7777 while ip remains the same...
2. This is High Five. Sadly I don't know how to check the protocol version.
3. Since this is a public server I think it is very probable that there is a GameGuard protection present :(

**Comment by npetrovski** [comment]
..forgot to ask you about a temp account or a domain/service I can create a temp account

**Comment by AlexKehl** [comment]
Created a test acc for this:
login: github
pwd: zsqm4b8q

**Comment by npetrovski** [comment]
Yeah.... The account works and I managed to create a new character, but even if I use the original L2Client, I get disconnected just after I select a character. 

This looks to me like a customization made for this public server (most probably GG protection). What's the website I can check and download the "system" directory and try get more information from it?

**Comment by AlexKehl** [comment]
https://www.rpg-club.com/lineage-2/en/download.html

**Comment by MattSmilin** [comment]
They have bot protection which, I think, changes how server is speaking with the client. I doubt you'll be able to connect without a serious investment.

**Comment by npetrovski** [comment]
I agree with @MattSmilin . I am closing this ticket now - if I find something I will let you know @AlexKehl
