### ISSUE TITLE
Failed to run npm run compile

### ISSUE THREAD

**Issue by 0xUnk** [npetrovski/l2js-client#55]
Hi @npetrovski.

I found a bug when running the command `npm run compile`
when executing the command, it is leaving the files below with only the import empty.

`build-index.js` is corrupting the files preventing the build from completing successfully.

src/commands/index.ts
```
 export default {
  
  };
```

src/network/incoming/game/index.ts

```
export {

};
```

src/network/incoming/login/index.ts

```
export {

};
```

src/network/mutators/game/index.ts

```
export default [

];
```

src/network/mutators/login/index.ts

<img width="911" alt="image" src="https://user-images.githubusercontent.com/96560489/190952430-d4685e8f-e03e-40e7-9c53-8e9ca05405d7.png">

Thank you!

**Comment by w3nder** [comment]
@0xUnk 

Hi how are you?
path problem, you are building on a platform other than Windows,
to solve is very simple.

const fullPath = `${dirname}\\${file}`; 
for 
const fullPath = `${dirname}${path.sep}${file}`;

**Comment by 0xUnk** [comment]
@w3nder thks
