### ISSUE TITLE
Latest versions are not published to NPM

### ISSUE THREAD

**Issue by Tamango92** [npetrovski/l2js-client#8]
At the moment, version 0.0.4 is installed via "npm install l2js-client". Later versions are not available. 
Taking the fact, that the config was changed in newer versions, it is impossible to run examples from readme  file.

Please, publish fresh versions to npm. :)

**Comment by npetrovski** [comment]
Hi @Tamango92  - yes, you are right, I have to publish the latest version, but before that I just want to make sure all breaking changes I did (configuration) will pass some tests.

**Comment by npetrovski** [comment]
Lates version is now published.
